/**
 * API Zod Schemas Export - Single Source of Truth
 *
 * DO NOT EDIT MANUALLY - Auto-generated by orval
 * Generated from: src/api-spec/openapi.yaml
 *
 * ============================================
 * ORGANIZATION: By Domain (Single File Per Domain)
 * ============================================
 *
 * This is the PRIMARY and ONLY source for:
 * ✓ Request/Response validation
 * ✓ Query parameter schemas
 * ✓ Route parameter schemas
 * ✓ Request body schemas
 *
 * DO NOT create duplicate types in other folders.
 * All types needed for API validation are here.
 *
 * ============================================
 * IMPORTING FROM HERE
 * ============================================
 *
 * // ✅ Correct - Import validation schemas
 * import {
 *   ListMenuItemsResponse,
 *   GetMenuItemParams,
 *   ListMenuItemsQueryParams
 * } from '../api-zod';
 *
 * // ✅ In routes - Use for validation
 * router.get('/items/:id', validateParams(GetMenuItemParams), ...)
 * router.get('/items', validateQuery(ListMenuItemsQueryParams), ...)
 * res.json(ListMenuItemsResponse.parse(items));
 *
 * ============================================
 * SCHEMAS BY DOMAIN
 * ============================================
 *
 * blog.ts:
 *   - ListBlogPostsQueryParams
 *   - ListBlogPostsResponse
 *   - GetBlogPostParams
 *   - GetBlogPostResponse
 *
 * menu.ts:
 *   - ListCategoriesResponse
 *   - ListMenuItemsQueryParams
 *   - ListMenuItemsResponse
 *   - GetFeaturedItemsResponse
 *   - GetMenuItemParams
 *   - GetMenuItemResponse
 *
 * chefs.ts:
 *   - ListChefsResponse
 *   - GetChefParams
 *   - GetChefResponse
 *
 * testimonials.ts:
 *   - ListTestimonialsQueryParams
 *   - ListTestimonialsResponse
 *
 * contact.ts:
 *   - SubmitContactBody
 *   - SubmitOfficeInquiryBody
 *
 * subscriptions.ts:
 *   - ListSubscriptionPlansResponse
 *
 * stats.ts:
 *   - GetSiteSummaryResponse
 *
 * health.ts:
 *   - HealthCheckResponse
 */

export * from "./generated/schemas";

// Legacy: Keep types folder exports for backward compatibility
// These are auto-generated and not edited manually
export * from "./generated/types";


